vich_uploader:
    db_driver: orm

    metadata:
        auto_detection: false

    mappings:
        imagen:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true
